sudo: required
language: node_js
node_js:
- 'node'
addons:
  ssh_known_hosts: surfboard.7hci.com
before_install:
- openssl aes-256-cbc -K $encrypted_07d8fc5b1702_key -iv $encrypted_07d8fc5b1702_iv -in deploy-key.enc -out deploy-key -d
before_script:
- npm run build
- npm install -g casperjs
script:
- npm run lint
- npm run test
after_success:
- eval `ssh-agent -s` && chmod 600 deploy-key && ssh-add deploy-key
- sed -i "1s/^/export TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST\n/" deploy.sh
- echo deploy.sh
- ssh deploy@surfboard.7hci.com "$(< deploy.sh)"