sudo: required
language: node_js
node_js:
- '6'
services:
- docker
addons:
  ssh_known_hosts: surfboard.7hci.com
  hosts: db
before_install:
- sudo service postgresql stop
- openssl aes-256-cbc -K $encrypted_539bb293c3a5_key -iv $encrypted_539bb293c3a5_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv development.js config/development.js
install:
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/1.13.0/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
before_script:
- docker build . -q -t surfboard_app
- docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
- docker tag surfboard_app:latest $DOCKER_USERNAME/surfboard:production
- docker push $DOCKER_USERNAME/surfboard:production
- docker-compose pull && docker-compose up -d
script:
- docker exec -t surfboard_app_1 npm run lint
- docker exec -t surfboard_app_1 npm run test
after_success:
- eval `ssh-agent -s` && chmod 600 deploy-key && ssh-add deploy-key
- scp -rp docker-compose.yml deploy@surfboard.7hci.com:/home/deploy/surfboard
- sed -i "1s/^/docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD\n/" deploy.sh
- ssh deploy@surfboard.7hci.com "$(< deploy.sh)"
notifications:
  email: false
  slack:
    secure: 1Pil28Ceia/EFc4awJwzwiONUcGG8oGRWkE6wVZtHk56C+C3KRGvoZi10oy7VKPzwheXQRFHuBqO+8joPc2E90v387g8pVvPVwQe8a5QcoIPNN6ErnlHshviN7n1nJy0xXEknLkBrtrXGqFuUdWzXBR6p0kx1QFU9Ljo/KNMVHBesiFvxrPEJCLQIANTUhWVBXeFqjdMWqKCbdVYYqjtx88FLhh1onnos2cEOp/2GOYlF9GXR5hXbstObaQpCt87jRSSDNZkgq8Sy6Rkg9zeTah3GG++3vHBRgC1bNr4I4yKzLc03gViJoLd+bHzMpa8fmP6i7CbPG69NMP4EB37z5UCxYUdJVbRJRpuIRZBFyXzw4kjliJW1ysvBA3+qzdaYiR1msy/DMNQcMUxx2GoF8F3zjqpqsqago/zILX3je3eO6UkSWFBZzVzZBXlgX9IOd5HTHECf2Q2XAV3PolMVsIhSw6Ioa+WTbVU2QC0bEcy5+2xU/lUk46XNK3ZX3kuylBhcBmXt1RPpVHWRIdZkCF7IK3JPRu0HOc/YNQwN5ofG20TJlytGL16OhtFNf6Z7fFqxVgIMbCpaXopMDsNPHdE7Jf6U8kG1gK2fq9bYHudJB+g60Z3lO5HGJq+nB6ZsioMx8czZEhT6DVl9iiMKNcM0oetC02Ya6DPlv5SPPI=