version: '2.1'

services:
  db:
    image: postgres:9.6
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=surfboard
      - POSTGRES_USER=surfboard
    healthcheck:
      test: ["CMD-SHELL", "psql -h localhost -U surfboard -c '\\l'"]
      interval: 30s
      timeout: 30s
      retries: 4
      
  app:
    image: danielrearden/surfboard:production
    ports:
      - 5000:5000
    links:
      - db
    depends_on:
      db:
        condition: service_healthy

  proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    links:
      - app:app