TRELLO_KEY = ""
TRELLO_TOKEN = ""

TRELLO_TEAM = ""
DANIEL_TRELLO_ID = ""
SCOTT_TRELLO_ID = ""
MEMBER_IDS = {"Daniel": DANIEL_TRELLO_ID,
              "Scott": SCOTT_TRELLO_ID}

SLACK_TOKEN = ""

HR_CONTRACTOR_FOLDER = ""
HR_FORMS_FOLDER = ""
TASKS_SPREADSHEET = ""
W9 = ""
W8 = ""
MSSA = ""
DIRECT_DEPOSIT = ""
BACKGROUND_CHECK = ""
